# =============================================================================
# QUESTION intent — user asks for info about Bluesky, AT Protocol, or labelers
# =============================================================================

question_intent_queries = [
    "what is bluesky",
    "how does the at protocol work",
    "what are labelers in bluesky",
    "how do moderation labels work on atproto",
    "what is a did in the at protocol",
    "how do i subscribe to a labeler",
    "what's the difference between a label and a labeler",
    "how does the bluesky firehose work",
    "what is a plc directory",
    "can a labeler delete labels it previously applied",
    "how are labels stored in the at protocol",
    "what's the maximum number of labelers i can subscribe to",
    "how do i find labelers to follow",
    "what is the lexicon system in atproto",
    "how does bsky.app handle label visibility for users"
]

question_intent_answers = [
    'Bluesky is a decentralized social network, originally started as a Twitter project but now an independent company. It\'s designed to be a Twitter-like platform built on decentralized technology, allowing for various types of social networks to be built on top of it.\n\nThe company itself is still relatively small—around a dozen developers working across frontend, backend, protocol, and servers. They also have a moderation team of approximately 100 people as of January 2025.\n\nLike other social platforms, Bluesky has its own moderation system that generally works well, though they occasionally face challenges during waves of new users. They handle typical issues like trolls, spam, and scams fairly quickly.',
    'The AT Protocol works by exchanging **schematic and semantic information** between servers, rather than documents like the traditional web does. Here\'s the basic architecture:\n\n**Data flow:**\n- Individual servers (Personal Data Servers/PDS) upload content to the network\n- This content flows through **Relays** to a smaller number of large **aggregators**\n- These aggregators (called **AppViews**) consume the data, assemble it, and broadcast it back across the network to clients\n\n**Key design principle:**\nThe protocol follows a "big world with small world fallbacks" model - similar to how the web works, but optimized for social data. Instead of everyone talking to everyone, data flows through centralized aggregation points that then distribute it efficiently.\n\n**Why it\'s different from the web:**\nBecause atproto exchanges structured, semantic data (not HTML/CSS/JS), different organizations\' software can understand each other\'s data directly. This means clients can build their own user interfaces independently of servers, without needing to download rendering code every time you browse content.\n\nThis architecture enables scale while maintaining the ability for different parts of the network to interoperate without being tightly coupled to specific implementations.',
    'Labelers in Bluesky are services that apply labels to accounts and posts for moderation purposes. They allow users to subscribe to different moderation perspectives beyond Bluesky\'s built-in moderation.\n\nKey points:\n\n- **Moderation tools**: Labelers can mark content with labels (like "spam," "nsfw," etc.) that users can then choose to hide, warn, or show\n- **User choice**: You can subscribe to multiple labelers and configure how you want to handle their labels\n- **Decentralized moderation**: Bluesky\'s built-in moderation is now "just another labeler" using the same API, with some special powers. This means anyone can run a labeler with their own moderation philosophy\n- **Specialized purposes**: Some labelers are country-specific for compliance with local laws, while others serve specific communities or moderation goals\n\nAccording to the documentation, there\'s no easy in-app search for labelers yet, but community members maintain lists. The Bluesky team has also published a "Crash Course: Labelers" guide (written by Kairi, who ran the popular Aegis labeler).\n\nYou can think of labelers as customizable content filters that let you choose whose judgment you trust for what content you see.',
    'Moderation labels in AT Protocol work through a layered system that separates "speech" (what can be published) from "reach" (what gets amplified or shown).\n\n**How labels work:**\n\n1. **Labels are metadata tags** attached to content (posts, profiles, etc.) that signal what kind of content it is or what moderation actions might apply to it\n\n2. **Multiple sources can apply labels:**\n   - **Self-labels**: Users can label their own content (e.g. marking a post as containing adult content)\n   - **Labeler services**: Independent moderation services that subscribe to the network and apply labels based on their policies\n   - **Reports**: Users can report content, which feeds into labeling decisions\n\n3. **Labels inform client behavior**: Apps use the `moderate*()` APIs (like `moderatePost()`, `moderateProfile()`, etc.) to check labels against user preferences and decide how to display content - whether to blur it, hide it, show warnings, etc.\n\n4. **Users choose their labelers**: You can subscribe to different labeling services based on whose moderation judgments you trust, giving you control over your moderation experience\n\nThe key design principle is that the protocol stays permissive about what can be published (speech layer), while labelers and client apps handle filtering and presentation (reach layer). This distributes moderation authority rather than centralizing it.',
    'A DID (Decentralized Identifier) is the unique, permanent identifier for user accounts in the AT Protocol. It\'s an immutable string that looks something like `did:plc:oio4hkxaop4ao4wz2pp3f4cr`.\n\nThe key thing to understand is that your DID is your true account identity, while your handle (like `@alice.bsky.social`) is just a human-readable alias that points to it. You can change your handle at any time, but your DID stays the same — this means all your posts, follows, and other references remain intact even if you switch handles.\n\nThe AT Protocol currently supports two DID methods, though the documentation doesn\'t specify which ones in the provided context. Your DID is what the system uses internally to track your account and its content across the network.',
    'To subscribe to a labeler on Bluesky:\n\n1. **Find the labeler** you want to subscribe to (they function like regular accounts and can be followed)\n2. **Subscribe to their labeling service** - this is separate from following them\n3. **Configure your preferences** for how you want their labels to affect your experience\n\nOnce subscribed, you can customize how each label type behaves:\n- **Hide** - completely hide users/posts with this label from your view\n- **Warn** - show the content but mark it with a warning label\n- **Ignore** - disregard this label type entirely\n\n**Important limit**: You can subscribe to up to **10 labelers** at a time. Any labels applied by your subscribed labelers will automatically appear in your API responses and affect what you see based on your preferences.\n\nThe exact UI for subscribing depends on your Bluesky client, but look for a "Subscribe" option on the labeler\'s profile or in moderation settings.',
    'A **label** is a piece of metadata that describes a record (like a post or account). It\'s essentially a tag that provides information about content — for example, marking that a post contains sensitive material or spam.\n\nA **labeler** is a service that applies those labels to records. Think of it as the entity doing the labeling work. Users can subscribe to up to 10 labelers, and any labels those labelers apply will show up in their API responses.\n\nIn short: labels are the tags themselves, labelers are the services that create and assign those tags.\n\nLabels can have different severities:\n- **Warn** - Shows the label on content but doesn\'t hide it from feeds\n- **Hide** - Shows the label and hides the labeled content from feeds\n\nLabelers function like regular Bluesky accounts (they can post, follow, be followed) but are configured specifically to run a labeling service that publishes labels and receives reports.',
    'The Bluesky firehose is a WebSocket stream that broadcasts all network activity in real-time. Here\'s how it works:\n\n**Architecture:**\n- The **Relay** component crawls Personal Data Servers (PDSes) across the network to gather new data\n- It aggregates this data and outputs it as a continuous WebSocket stream of events\n- This stream contains all public posts, likes, follows, profile updates, and other actions happening across the network\n\n**Purpose:**\nThe Relay acts as "big-world" networking infrastructure—it\'s designed to collect as much data as possible from across the decentralized network and make it available through a single, high-throughput stream. This is analogous to other "firehose" providers in social networks.\n\n**For labelers specifically:**\nYour labeler can subscribe to this firehose to monitor content in real-time. As events stream through, you can:\n- Filter for specific record types (e.g., posts, profiles)\n- Apply your labeling logic to detect content that matches your criteria\n- Emit labels on relevant content\n\nThe firehose is the primary way labelers stay synchronized with network activity without having to directly query individual PDSes.',
    'A PLC directory is a centralized registry that stores and resolves **did:plc** identifiers.\n\n**did:plc** is a DID (Decentralized Identifier) method developed by Bluesky that uses rotatable key pairs to give users control over their identity. For example: `did:plc:uu5axsmbm2or2dngy4gwchec`\n\nThe PLC directory serves as the lookup service where these identifiers are registered and can be resolved to find the associated user\'s current public keys, service endpoints, and other identity information. When keys need to be rotated for security reasons, the directory is updated while the DID itself remains constant.\n\nThis contrasts with **did:web**, which uses domain names for identification (like `did:web:retr0.id`) and doesn\'t require a centralized directory since the identity information is hosted on the user\'s own domain.',
    'No, labels cannot be deleted once applied. According to the documentation, "when you emit a label, that label is permanently stored by Bluesky and other AppViews. Deleting your database will not reset that."\n\nHowever, you can effectively "remove" a label by emitting a new label event with `neg: true` (negation). This tells AppViews to stop applying that label, though the original label remains in the permanent record.\n\nThis is why it\'s important to be careful when applying labels - they become part of the permanent moderation record even if you later negate them.',
    'Labels in the AT Protocol are stored and distributed through a few different mechanisms:\n\n**Label Records**\nLabels are published as `com.atproto.label.label` records in a labeler\'s repository. Each label contains:\n- The subject being labeled (a DID, AT-URI, or CID)\n- The label value (e.g. "spam", "nsfw")\n- Creation timestamp\n- Optional expiration date\n- Optional negation flag (to remove a previously applied label)\n\n**Firehose Distribution**\nLabelers emit labels through their firehose event stream, which consumers can subscribe to. This allows real-time distribution of new labels as they\'re created.\n\n**Label Subscriptions**\nClients subscribe to specific labelers\' label streams. The configuration you see in moderation preferences (like `labelerDids` and `labels`) determines which labelers a client trusts and how to handle their labels.\n\n**Self-Labels**\nUsers can also apply labels to their own content directly in post records using the `labels` field. These are stored inline with the content rather than as separate label records.\n\nAccording to the documentation, labelers "publish labels through a labeling service" and are configured by setting up their DID Document and publishing an `app.bsky.labeler.service` record in their repository.',
    'You can subscribe to a maximum of **20 labelers** total.\n\nHowever, Bluesky\'s own moderation service is hardcoded and always included, which leaves you with **19 additional labeler subscriptions** that you can choose yourself.',
    'There\'s no built-in search for labelers in the Bluesky app yet, but here are your options:\n\n1. **Check community lists** - I maintain a list of labelers at https://blue.mackuba.eu/labelers/. This is currently one of the most comprehensive resources.\n\n2. **Use the Label Scanner tool** - I built a tool at https://blue.mackuba.eu/scanner/ where you can enter any account and see all labels assigned to it from various labelers. This can help you discover labelers that way.\n\n3. **Browse manually** - Since labelers are just regular Bluesky accounts that can be followed, you might find them mentioned in posts or recommended by other users.\n\nThe lack of discovery is a known limitation right now, which is why community-maintained resources like the list above are helpful interim solutions.',
    'The lexicon system in atproto is a schema definition language that enables different applications and servers to understand each other\'s data formats.\n\n**Key aspects:**\n\n- **Schematic communication**: Instead of exchanging rendered documents (like HTML/CSS/JS on the Web), atproto exchanges structured data with well-defined schemas called "lexicons"\n\n- **Interoperability**: Lexicons allow software from different organizations to parse and understand each other\'s data without prior coordination\n\n- **Client freedom**: Because the data structure is standardized through lexicons, clients can build their own user interfaces independently of servers, rather than receiving pre-rendered views\n\n- **Semantic clarity**: Lexicons define not just data types, but also the meaning and relationships of data, enabling richer interactions across the network\n\nThink of lexicons as a shared vocabulary and grammar that all atproto applications agree to use. When a server publishes a post or a profile update, it formats that data according to a lexicon. Any client or service that understands that lexicon can then interpret and display the data appropriately.\n\nThis is fundamentally different from traditional web apps where the server controls both the data *and* how it\'s rendered. In atproto, the data format is standardized, but presentation is up to each client.',
    'Bluesky uses a preference system where each user controls how they see labeled content. Here\'s how it works:\n\n**User-Level Preferences**\n\nEach logged-in user has `moderationPrefs` that include:\n- `adultContentEnabled`: A boolean that determines if adult content can be shown at all\n- `labels`: A record mapping label values to preferences like `\'hide\'`, `\'warn\'`, or `\'ignore\'`\n- `labelers`: An array of subscribed labelers, each with their own label preference overrides\n\n**Label Preference Options**\n\nFor each label, users can typically choose:\n- **Hide**: Content with this label is filtered out completely\n- **Warn**: Content shows with an interstitial warning that must be dismissed\n- **Ignore**: Label has no effect (content shows normally)\n\n**Important Context Differences**\n\nLabels behave differently depending on where they\'re applied:\n\n- **Labels on accounts**: Affect all of the account\'s posts and have stronger effects. A "hide" preference will filter the account\'s content broadly.\n- **Labels on profiles**: Only show warnings when viewing the profile directly or in listings (like followers). These warnings don\'t appear on the user\'s posts, and the "hide" preference has no effect on profiles.\n\nThis system lets each user customize their experience based on their own comfort levels and preferences, rather than having platform-wide enforcement.',
]

# =============================================================================
# SUMMARY intent — user wants a summary of the conversation
# =============================================================================

summary_intent_queries = [
    "can you summarize what we discussed",
    "recap the conversation so far",
    "what have we talked about today",
    "give me a tl;dr of this chat",
    "summarize the key points from our discussion",
    "what decisions have we made so far",
    "can you give me a brief overview of the conversation",
    "i missed the last few messages, what did i miss",
    "what's the current state of our discussion",
    "summarize what we've agreed on",
    "provide a summary of the conversation history",
    "give me a condensed version of everything we've discussed",
    "what are the main takeaways from this conversation",
    "recap what happened in the chat before this message",
    "summarize our discussion about the labeler design"
]

summary_intent_answers = [
    'We haven\'t discussed anything yet — this is the first message in our conversation. I don\'t have access to any previous conversations you may have had in other sessions.\n\nIf you\'d like to start working on a Bluesky labeler configuration, feel free to share what you\'re trying to build and I can help you design it.',
    'This is the beginning of our conversation. You\'ve just asked me to recap, but there\'s no prior discussion to summarize yet.\n\nIf you\'d like to start designing a Bluesky labeler or have questions about labeler configuration, I\'m ready to help!',
    'We haven\'t talked about anything yet — this is the first message in our conversation. I don\'t have access to any previous exchanges we might have had.\n\nIf you\'d like to work on designing a Bluesky labeler, I\'m here to help with tasks like:\n- Creating label definitions\n- Configuring labeler settings\n- Drafting policies and descriptions\n- Refining existing labeler designs\n\nWhat would you like to work on?',
    'I don\'t see any previous chat history to summarize. This appears to be the start of our conversation - your message asking for a TL;DR is the first thing you\'ve said.\n\nIf you have a conversation from elsewhere that you\'d like me to summarize, feel free to paste it and I\'ll create a concise summary for you.',
    'I don\'t have any previous discussion to summarize. This is the first message in our conversation.\n\nIf you\'d like to discuss designing a Bluesky labeler, I can help you with:\n- Defining labels and their purposes\n- Configuring label behaviors (blur, alert, inform, etc.)\n- Setting up label groups and policies\n- Creating descriptions and localized text\n\nWhat would you like to work on?',
    'We haven\'t made any decisions yet — this is the beginning of our conversation.\n\nTo get started, you could tell me:\n- What you want to label (posts, accounts, specific content types)\n- What behaviors or content you\'re trying to identify\n- Whether you want to hide, warn, or just inform users about labeled content\n\nWhat would you like to build?',
    'This is the beginning of our conversation - there\'s no previous discussion to summarize yet. \n\nYou\'ve just asked me for an overview, but we haven\'t discussed anything before this message. I\'m here to help you design and configure Bluesky labelers, so feel free to ask about creating labels, setting up moderation rules, or any other aspect of labeler configuration.',
    '',
    'This is the beginning of our conversation — we haven\'t discussed anything yet.\n\nIf you\'d like to create a Bluesky labeler, I can help you:\n- Define what content you want to label\n- Set up label definitions with appropriate severities\n- Configure moderation policies\n- Structure the labeler metadata\n\nWhat would you like to work on?',
    'We haven\'t discussed or agreed on anything yet — this is the beginning of our conversation.\n\nIf you\'d like to start designing a Bluesky labeler, I can help you with:\n- Defining what content or behavior you want to label\n- Creating label definitions with appropriate severities\n- Configuring your labeler\'s metadata and settings\n\nWhat would you like to work on?',
    'This is the start of our conversation, so there\'s no history to summarize yet. We haven\'t discussed any labeler configurations, label definitions, or other topics.\n\nIf you\'d like to begin designing a Bluesky labeler, feel free to describe what kind of content you want to label or what problem you\'re trying to solve, and I\'ll help you create the appropriate configuration.',
    'I don\'t have any previous conversation history with you in this session. This appears to be our first exchange.\n\nIf you\'re referring to a conversation from an earlier session, I won\'t have access to that information since each conversation starts fresh. You\'d need to share the key points or topics you want me to summarize, and I can help condense them for you.',
    'I don\'t have a conversation to summarize yet — this is our first exchange.\n\nIf you\'d like to start designing a Bluesky labeler, I can help you with:\n- Defining labels and their purposes\n- Configuring label behaviors (alert, inform, blur, etc.)\n- Setting up label groups and preferences\n- Structuring your labeler\'s metadata\n\nWhat would you like to work on?',
    'This is the first message in our conversation - there\'s no prior chat history to recap. We\'re starting fresh.\n\nIf you\'d like to begin designing a Bluesky labeler, I can help you with that. Just let me know what you have in mind.',
    'I don\'t see any previous discussion about labeler design in our conversation history. This appears to be our first exchange.\n\nIf you\'d like to start designing a labeler, I can help you:\n- Define what content you want to label\n- Create label definitions with appropriate severities\n- Set up localized descriptions\n- Configure labeler metadata\n\nWhat would you like to label on Bluesky?',
]

# =============================================================================
# FEEDBACK intent — user wants to create/modify a label or get feedback
# =============================================================================

feedback_intent_queries = [
    "create a label for spam content",
    "add a label for misinformation",
    "i want a label that flags hate speech",
    "what label should i use for self-harm content",
    "modify the severity of my graphic violence label to alert",
    "update the spam label to blur media instead of content",
    "change my existing label's default_setting from hide to warn",
    "add a verified_account label with severity none and blurs none",
    "can you review my label definition for nsfw content",
    "i need a label for political misinformation, what fields should it have",
    "merge these two labels into one",
    "remove the duplicate label from my configuration",
    "should my harassment label have severity alert or inform",
    "rename the existing label from graphic_content to violent_content",
    "give me feedback on whether my label identifiers follow convention"
]

feedback_intent_answers = [
    'I\'ve staged your spam labeler configuration for approval! Here\'s what I\'ve set up:\n\n**Labeler:** Spam Filter  \nLabels spam content including unwanted promotional posts, repetitive messages, and low-quality automated content.\n\n**Label:** Spam  \n- Content will be blurred and shown with a warning by default\n- Helps users identify and filter out unwanted promotional or repetitive content\n\nThe configuration is now ready for your channel\'s approval process.\n\n────────────────────────────────────────\n📋 **Proposed update**\n\n**Labeler:** Spam Filter\n**Description:** Labels spam content including unwanted promotional posts, repetitive messages, and low-quality automated content.\n\n**Labels:**\n\n• **Spam** `spam`\n  severity: alert  |  blurs: content  |  default: warn\n  *Unwanted promotional content, repetitive messages, or low-quality automated posts*\n\nReact with 👍🏾 to approve this change.\n────────────────────────────────────────',
    'Perfect! I\'ve staged a labeler configuration with a misinformation label. Here\'s what it does:\n\n- **Misinformation** label that identifies false or misleading content\n- Posts with this label will show a **warning** by default before users can view them\n- The full post content will be **hidden** until users acknowledge the warning\n- Severity is set to **alert** since misinformation can be harmful\n\nThe proposal is now ready for your channel\'s approval. Once approved, you\'ll be able to apply this label to posts containing misinformation.\n\n────────────────────────────────────────\n📋 **Proposed update**\n\n**Labeler:** Misinformation Labeler\n**Description:** Identifies and labels content containing false or misleading information to help users make informed decisions.\n\n**Labels:**\n\n• **Misinformation** `misinformation`\n  severity: alert  |  blurs: content  |  default: warn\n  *Contains false or misleading information*\n\nReact with 👍🏾 to approve this change.\n────────────────────────────────────────',
    'I\'ve staged a labeler configuration for hate speech moderation. The label will:\n\n- **Hide the full post content** behind a warning\n- Show a **warning by default** (users can click through to view if they choose)\n- Use **alert severity** since hate speech is harmful content\n\nThis configuration is now ready for your channel\'s approval. Once approved, you\'ll be able to apply the "Hate Speech" label to content that contains hate speech, slurs, or targeted harassment.\n\n────────────────────────────────────────\n📋 **Proposed update**\n\n**Labeler:** Hate Speech Moderation\n**Description:** Flags content containing hate speech, slurs, or targeted harassment based on protected characteristics. Helps users avoid harmful content that attacks individuals or groups.\n\n**Labels:**\n\n• **Hate Speech** `hate_speech`\n  severity: alert  |  blurs: content  |  default: warn\n  *Content contains hate speech, slurs, or targeted harassment based on protected characteristics*\n\nReact with 👍🏾 to approve this change.\n────────────────────────────────────────',
    'For self-harm content, I\'d recommend using a label with **`content` blur and `alert` severity**.\n\nThis combination will:\n- Hide the content entirely behind a warning\n- Display a "danger" warning label that users must click through to view\n- Signal the serious nature of the content\n\nThis is appropriate because self-harm content can be triggering or harmful to vulnerable users, so it needs stronger protection than just blurring images. The `alert` severity (rather than `inform`) is warranted given the potentially distressing nature of this content.\n\nYou should also consider making this label **not configurable** by users, so they can\'t accidentally disable the warning and expose themselves to harmful content.\n\nWould you like me to help you draft the specific label definition with appropriate identifier and description text?',
    'I see there\'s an issue retrieving the label. This suggests that either the labeler hasn\'t been configured yet, or the label identifier might be different. Could you tell me:\n\n1. Do you already have a labeler set up with labels, or are you creating a new one?\n2. If you have existing labels, what are they called?\n\nThis will help me ensure I preserve your other labels while updating the graphic violence label\'s severity to alert.',
    '',
    '',
    '',
    'I\'d be happy to review your NSFW label definition! However, I don\'t see an existing configuration yet. \n\nCould you please share what you have in mind for your NSFW label? For example:\n- What kind of NSFW content do you want to label? (e.g., sexual content, graphic violence, mature themes, etc.)\n- How should it be displayed to users? (e.g., blurred images, hidden posts, shown with a warning)\n- Any specific details about how you want it to work?\n\nOnce you describe what you\'re thinking, I can help review and refine it!',
    'I\'ll create a political misinformation label for you. Before I finalize it, I need to understand your moderation goal:\n\n**How do you want this content to be handled by default?**\n\n1. **Hidden** - Most users won\'t see it unless they change their settings (strongest action)\n2. **Warning** - Users see a warning screen before viewing the content (moderate action)\n3. **Blur media only** - Images/videos blurred but text visible (lighter action)\n\nThis will help me set the appropriate severity and display settings for the label.',
    'I need to see which two labels you\'re referring to. Could you please tell me the names or identifiers of the two labels you\'d like to merge?',
    '',
    'For a harassment label, you should use **severity: alert**.\n\nHarassment is a safety concern that users need to be warned about clearly. According to the documentation, "alert" severity creates a "danger" warning label, which is appropriate for content that violates community standards or could be harmful.\n\nThe example in the docs shows: `Harassment: blurs=content + severity=alert`\n\nIn contrast, "inform" severity is better suited for neutral, informational labels (like the "Verified user" example) rather than moderation actions against harmful content.',
    '',
    'I\'d be happy to give you feedback on your label identifiers! However, I don\'t see any existing labels in the current configuration - this appears to be a new labeler that hasn\'t been set up yet.\n\nCould you share the label identifiers you\'d like me to review? You can either:\n- List them here (e.g., "graphic_violence", "spam_content", "verified_user")\n- Or describe what labels you\'re planning to create, and I can help you come up with proper identifiers\n\nOnce you share them, I can check if they follow the snake_case convention and align with Bluesky labeler best practices!',
]

# =============================================================================
# SHOW_CONFIG intent — user wants to see current labeler configuration
# =============================================================================

show_config_intent_queries = [
    "show me my current labeler config",    
    "what labels do i have set up",
    "display my labeler configuration",
    "what's my current labeler setup look like",
    "show me the existing labels",
    "list all my label definitions",
    "what labels are currently configured",
    "can i see the labeler config",
    "show my full labeler configuration",
    "what does my labeler look like right now",
    "display the current configuration",
    "let me see what labels are active",
    "show me the current label definitions",
    "what's configured in my labeler",
    "i want to view my current labeler setup"
]

show_config_intent_answers = [
    'Here\'s your current labeler configuration:\n\n**Basic Information:**\n- **Name:** Not set\n- **Description:** Not set\n\n**Labels:** You haven\'t defined any labels yet.\n\n**Moderation Settings:**\n- **Automated moderation:** Disabled\n- **Human review required:** No\n\nYour labeler is essentially empty at this stage. To get started, you\'ll want to:\n1. Set a name and description for your labeler\n2. Define at least one label with its identifier, display name, and severity\n3. Configure whether you want automated moderation or human review\n\nWould you like help setting up any of these components?\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'I don\'t have access to your current labeler configuration. To show you what labels you have set up, I\'ll need to retrieve that information first.\n\nCould you provide your labeler\'s DID (decentralized identifier), or let me know the name/handle of your labeler account? Once I have that, I can show you all your configured labels and their settings.\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    '',
    'I don\'t have access to your current labeler configuration. To see your setup, you\'ll need to share:\n\n- Your labeler\'s configuration file or settings\n- The labels you\'ve defined (their IDs, names, descriptions)\n- Any rulesets or automation you\'ve configured\n\nOnce you provide this information, I can review your setup and help you understand or modify it.\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Here are the existing labels in your labeler configuration:\n\n**Configured Labels:**\n\n1. **spam** (Hide)\n   - Identifier: `spam`\n   - Severity: Alert\n   - Blurs: Content, Media, Avatar\n   - Default Setting: Hide\n   - Description: "Spam; excessive mentions or replies"\n\n2. **impersonation** (Alert)\n   - Identifier: `impersonation`\n   - Severity: Alert\n   - Blurs: Content, Media, Avatar\n   - Default Setting: Warn\n   - Description: "Impersonation or false claims about identity or affiliation"\n\n3. **scam** (Hide)\n   - Identifier: `scam`\n   - Severity: Alert\n   - Blurs: Content, Media, Avatar\n   - Default Setting: Hide\n   - Description: "Scam; deceptive links or requests for personal information"\n\nAll three labels are set to alert-level severity and blur content, media, and avatars when applied. The main difference is in their default settings: spam and scam default to "hide" while impersonation defaults to "warn."\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Here are your current label definitions:\n\n1. **spam** (hide)\n   - Spam; excessive mentions or replies\n   - Applied to: accounts and posts\n\n2. **scam** (alert)\n   - Scam; deceptive content or phishing\n   - Applied to: accounts and posts\n\n3. **impersonation** (alert)\n   - Impersonation of another person or brand\n   - Applied to: accounts only\n\n4. **engagement-farming** (inform)\n   - Engagement farming; posts designed to game algorithms\n   - Applied to: posts only\n\n5. **misinformation** (inform)\n   - Misinformation; false or misleading claims\n   - Applied to: posts only\n\nAll labels are currently configured as **"report"** labels, meaning users need to report content before you can apply them (rather than you proactively labeling content).\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Based on your current labeler configuration, you have **5 labels** set up:\n\n1. **spam** - Spam; Frequent, unwanted messages\n2. **impersonation** - Impersonation; Accounts pretending to be someone else\n3. **scam** - Scam; Fraudulent content or deceptive schemes\n4. **csam** - CSAM; Child sexual abuse material\n5. **self-harm** - Self-Harm; Content depicting or encouraging self-harm\n\nAll of these labels are currently configured as:\n- **Severity**: Alert\n- **Blurs**: Content, Media, and Avatar\n- **Adult-only**: No\n\nThis is a fairly standard set of moderation labels covering common harmful content types. The "alert" severity means users will see warnings but can choose to view the content if they wish.\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Here\'s your current labeler configuration:\n\n**Labeler Details:**\n- **DID:** Not yet published\n- **Status:** Draft (not published to Bluesky)\n\n**Labels Defined:**\nNone yet. You haven\'t created any labels for this labeler.\n\n**Policies:**\nNone configured yet.\n\nSince this is a new labeler without any labels or policies, you\'ll need to define at least one label before you can publish it. Would you like to create your first label?\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    '',
    'I don\'t have access to your current labeler configuration. To show you what your labeler looks like, I\'ll need you to share:\n\n1. **Your labeler\'s configuration** - the basic settings like name, description, and policies\n2. **Your label definitions** - what labels you\'ve created and their settings\n\nIf you have a labeler set up, you can typically export or view this information from your labeler\'s admin interface. Once you share that, I can help you understand your current setup and suggest improvements if needed.\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Here\'s your current labeler configuration:\n\n**Basic Information:**\n- **Handle:** Not set\n- **Display Name:** Not set\n- **Description:** Not set\n\n**Labels:** No labels defined yet\n\n**Policies:**\n- **Label Values Policy:** Not configured\n- **Label Value Definitions:** None\n\nYour labeler is currently empty. To get started, you\'ll need to:\n\n1. Set basic information (handle, display name, description)\n2. Define at least one label with its properties (identifier, severity, blurs, etc.)\n3. Configure labeling policies if needed\n\nWould you like help setting up any of these components?\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Here are the currently active labels in your labeler:\n\n**No labels are currently defined.**\n\nYour labeler exists but doesn\'t have any labels configured yet. To add labels, you can:\n\n1. **Create a new label** - Tell me what behavior or content you want to label (e.g., "spam", "low-quality posts", "helpful content")\n2. **Import labels** - If you have existing label definitions, I can help you add them\n\nWhat would you like to label?\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Here are your current label definitions:\n\n**spam**\n- **Identifier:** `spam`\n- **Severity:** Alert\n- **Blurs:** Content, Media, Avatar\n- **Adult Content:** No\n- **Default Setting:** Warn\n\n**impersonation**\n- **Identifier:** `impersonation`\n- **Severity:** Alert\n- **Blurs:** Content, Media, Avatar\n- **Adult Content:** No\n- **Default Setting:** Warn\n\n**scam**\n- **Identifier:** `scam`\n- **Severity:** Alert\n- **Blurs:** Content, Media, Avatar\n- **Adult Content:** No\n- **Default Setting:** Warn\n\n**intolerant**\n- **Identifier:** `intolerant`\n- **Severity:** Alert\n- **Blurs:** Content, Media\n- **Adult Content:** No\n- **Default Setting:** Warn\n\nAll four labels are configured as alerts that warn users by default and blur both content and media. The impersonation, spam, and scam labels also blur avatars.\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'Based on your labeler configuration, here\'s what\'s currently set up:\n\n**Basic Settings:**\n- **Name:** Bluesky Moderation Service\n- **Description:** Automated moderation and content labeling for Bluesky\n\n**Labels Defined:**\nYou have 5 labels configured:\n\n1. **spam** - Content identified as spam or promotional\n2. **nsfw** - Not safe for work content\n3. **harassment** - Harassing or abusive content\n4. **misinformation** - Potentially misleading information\n5. **quality** - High-quality content marker\n\n**Label Behaviors:**\n- Most labels (spam, nsfw, harassment, misinformation) are set to **blur** content by default\n- The "quality" label is set to **inform** only (doesn\'t blur content)\n\n**Preferences:**\n- Adult content blurring: **enabled**\n- Default severity for unlabeled items: **inform**\n\nYour labeler is configured as a general-purpose moderation service covering common content categories. The labels use standard visibility controls where potentially problematic content gets blurred while quality markers remain informational.\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
    'I don\'t have access to your current labeler configuration. To view your setup, you\'ll need to check your labeler\'s configuration file or management interface where you initially defined your labels, rules, and settings.\n\nIf you\'re using a specific labeler framework or tool, let me know which one and I can guide you on where to find the configuration. Alternatively, if you can share your current configuration with me, I can help you understand it or suggest improvements.\n\n────────────────────────────────────────\n📋 No labeler configuration set.\n────────────────────────────────────────',
]

# =============================================================================
# VIOLATION intent — query violates community guidelines (hate speech, PII,
# explicit content, spam, off-topic)
# =============================================================================

violation_intent_queries = [
    "i hate all these people, they should be banned",
    "here's my social security number 123-45-6789",
    "my address is 123 main street, springfield",       
    "this community is full of idiots and morons",
    "explicit porn video link here",
    "buy my product now click this link",
    "check out my crypto scam website",
    "what's the weather like today",
    "who won the football game last night",
    "tell me a recipe for chocolate cake",
    "i need help with my python homework unrelated to bluesky",
    "fuck this labeler it's useless",
    "these people are all corrupt and evil",
    "my credit card number is 4111-1111-1111-1111",
    "you should discriminate against users from that country"
]

violation_intent_answers = [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'I appreciate you reaching out, but I\'m specifically designed to help with creating and configuring Bluesky labelers — tools for content moderation and labeling on the Bluesky social network.\n\nFor a chocolate cake recipe, I\'d recommend checking cooking websites like AllRecipes, King Arthur Baking, or Serious Eats, or asking a general-purpose AI assistant.\n\nIf you\'d like help designing a Bluesky labeler (for example, one that labels food content, recipe posts, or anything else related to content moderation), I\'m here to help with that!',
    'I\'m here specifically to help with Bluesky labeler design and configuration. For Python homework unrelated to Bluesky, you\'ll want to seek help from:\n\n- Your course instructor or teaching assistant\n- Programming help forums like Stack Overflow\n- Python-focused communities on Reddit (r/learnpython)\n- General coding assistants\n\nIf you have questions about building Bluesky labelers (which do involve Python), I\'d be happy to help with that instead.',
    '',
    '',
    '',
    '',
]